title: North Adriatic Go League
email: info@nagl.org
description: A cross-border alliance of stones and friendship.
baseurl: "/nagl.io" 
url: "https://oiram85.github.io/nagl.io/"

# Build settings
markdown: kramdown
permalink: /news/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/
    collections:
  events:
    output: true
    permalink: /events/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
